import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pluga Challenge Front",
  description: "Generated by create next app",
  icons: {
    icon: "https://assets.pluga.co/site/images/favicons/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
