'use client'

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from "react";
import "./globals.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en" data-theme="light">
      <head>
        <title>Pluga Challenge Front</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="https://assets.pluga.co/site/images/favicons/favicon-32x32.png" />
      </head>
      <body className="antialiased">
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
